export default {
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    imgBackground: {
        borderColor:"green",
        borderWidth:5,
        position: 'absolute',
        width: '150%',
        height: '90%',
        borderRadius: 300,
        top: '-10%',
    },
    headerText: {
        fontSize: 20,
        textAlign: "center",
        marginTop: 50,
        fontWeight: "bold"
    },
    circleImg: {
        width: '100%',
        height: '100%',
        borderRadius: 200 / 2,
    },
    circleImgConteiner: {
        width: 190,
        height: 190,
        borderRadius: 190 / 2,
    },
    userName: {
        textAlign: 'center',
        fontWeight: 'bold',
        color: 'white',
        fontSize: 16,
        marginTop: 15
    },
    userSubTitulo: {
        textAlign: 'center',
        fontWeight: 'bold',
        fontStyle: 'italic',
        fontSize: 16,
        color: 'white',
        paddingVertical: 5,
    },

    btnEditPerfil: {
        position: 'absolute',
        width: 70,
        height: 70,
        backgroundColor: 'white',
        borderRadius: 70 / 2,
        left: 10,
        top: '25%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnNotificacao: {
        position: 'absolute',
        width: 70,
        height: 70,
        backgroundColor: 'white',
        borderRadius: 70 / 2,
        top: '15%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnOds: {
        position: 'absolute',
        width: 70,
        height: 70,
        backgroundColor: 'white',
        borderRadius: 70 / 2,
        right: 10,
        top: '25%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnLogout: {
        position: 'absolute',
        width: 40,
        height: 40,
        backgroundColor: '#2AB940',
        borderRadius: 40 / 2,
        right: 10,
        bottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnTrocarImg: {
        position: 'absolute',
        width: 35,
        height: 35,
        backgroundColor: 'white',
        borderRadius: 40 / 2,
        right: 10,
        bottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnInfo:{
        position: 'absolute',
        width: 40,
        height: 40,
        backgroundColor: '#2AB940',
        borderRadius: 40 / 2,
        left: 10,
        bottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },

    NotificationCount: {
        position: 'absolute',
        width: 20,
        height: 20,
        backgroundColor: '#BB0000',
        borderRadius: 40/2,
        borderRadius: 40 / 2,
        borderColor: 'white',
        borderWidth: 2,
        bottom: 50,
        right: 7,
        alignItems:'center',
        justifyContent:'center',
        alignItems: 'center',
        justifyContent: 'center',
    }
};